from os import listdir, mkdir
from os.path import isfile, join, isdir

import nestedtext as nt


def create_model_file(output_folder, model):
    if not isdir(join(output_folder, 'models')):
        mkdir(join(output_folder, 'models'))
    with open(join(output_folder, 'models', model+'.py'), 'w+') as f:
        f.write('# This file was generated by sapiens\n')
        f.write('from engine import Base\n\n\n')
        f.write(f'Class {model}(Base):\n')

def create_properties(output_folder, model, fields):
    # fields are received as a list [field_name: some parameters separated by commas, ...]
    with open(join(output_folder, 'models', model+'.py'), 'w+') as f:
        pass

def create_models(design_folder, output_folder):
    for f in [f for f in listdir(design_folder) 
              if isfile(join(design_folder, f))
              and f[-3:] == '.nt'
              and f[:5] == 'model']:
        models = nt.load(join(design_folder, f), 'dict')
        for model in models:
            create_model_file(output_folder, model)
            for k in models[model]:
                if k == 'fields':
                    create_properties(output_folder, model, models[model][k])

def create_engine(design_folder, output_folder):
    if not isdir(join(output_folder, 'models')):
        mkdir(join(output_folder, 'models'))
    with open(join(output_folder, 'models', 'engine.py'), 'w+') as f:
        f.write('# This file was generated by sapiens\n')
        f.write('from sqlalchemy import create_engine\n')
        f.write('from sqlalchemy.ext.declarative import declarative_base\n\n\n')
        f.write("engine = create_engine('sqlite:///:memory:', echo=True)\n")
        f.write('Base = declarative_base()\n')
